name: Run Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-state: '3.x'

    - name: Run Challenge 06 Unit Tests
      run: |
        python3 -m unittest challenge_06_benefits_calculator/test_calculator.py

    - name: Run Challenge 10 Unit Tests
      run: |
        python3 -m unittest challenge_10_fraud_detection/test_detector.py
